"""Tests for backtest.broker (BACK-02, D-01). Implementations land in plan 04."""
import pytest

pytestmark = pytest.mark.skip(reason="implementation lands in plan 04")


def test_protocol_compliance(): ...
def test_no_future_leak(): ...
def test_send_order(): ...
def test_sl_tp_priority(): ...
def test_gap_fill(): ...
