"""Tests for backtest.engine (BACK-02, BACK-04, SC-6). Implementations land in plan 05."""
import pytest

pytestmark = pytest.mark.skip(reason="implementation lands in plan 05")


def test_engine_5bar_fixture(): ...
def test_decision_context(): ...
def test_equity_curve(): ...
def test_smoke_12month_under_60s(): ...
