"""Tests for backtest.loader (BACK-01). Implementations land in plan 02."""
import pytest

pytestmark = pytest.mark.skip(reason="implementation lands in plan 02")


def test_basic_load(): ...
def test_gmt6_utc_offset(): ...
def test_column_strip(): ...
def test_nfp_alignment(): ...
