"""Tests for backtest.walk_forward (BACK-05, D-06). Implementations land in plan 06."""
import pytest

pytestmark = pytest.mark.skip(reason="implementation lands in plan 06")


def test_no_overlap(): ...
def test_expanding_mode(): ...
def test_fold_cap(): ...
def test_temporal_order(): ...
